const baseUrl = 'https://ir-banks-info.github.io/logos/public'
export const bankData: Record<string, { name: string; logo: string }> = {
  '627412': { name: 'اقتصاد نوین', logo: `${baseUrl}/Eghtesad_Novin.svg` },
  '627381': { name: '(سپه) انصار', logo: `${baseUrl}/Ansar.svg` },
  '505785': { name: 'ایران زمین', logo: `${baseUrl}/Iran_Zamin.svg` },
  '622106': { name: 'پارسیان', logo: `${baseUrl}/Parsian.svg` },
  '639194': { name: 'پارسیان', logo: `${baseUrl}/Parsian.svg` },
  '627884': { name: 'پارسیان', logo: `${baseUrl}/Parsian.svg` },
  '639347': { name: 'پاسارگاد', logo: `${baseUrl}/Pasargad.svg` },
  '502229': { name: 'پاسارگاد', logo: `${baseUrl}/Pasargad.svg` },
  '636214': { name: 'آینده', logo: `${baseUrl}/Ayandeh.svg` },
  '627353': { name: 'تجارت', logo: `${baseUrl}/Tejarat.svg` },
  '585983': { name: 'تجارت', logo: `${baseUrl}/Tejarat.svg` },
  '502908': { name: 'توسعه تعاون', logo: `${baseUrl}/Tosee_Taavon.svg` },
  '627648': {
    name: 'توسعه صادرات ایران',
    logo: `${baseUrl}/Tosee_Saderat.svg`,
  },
  '207177': {
    name: 'توسعه صادرات ایران',
    logo: `${baseUrl}/Tosee_Saderat.svg`,
  },
  '636949': { name: 'حکمت ایرانیان (سپه)', logo: `${baseUrl}/Hekmat.svg` },
  '502938': { name: 'دی', logo: `${baseUrl}/Dey.svg` },
  '589463': { name: 'رفاه کارگران', logo: `${baseUrl}/Refah.svg` },
  '621986': { name: 'سامان', logo: `${baseUrl}/Saman.svg` },
  '589210': { name: 'سپه', logo: `${baseUrl}/Sepah.svg` },
  '639607': { name: 'سرمایه', logo: `${baseUrl}/Sarmayeh.svg` },
  '639346': { name: 'سینا', logo: `${baseUrl}/Sina.svg` },
  '502806': { name: 'شهر', logo: `${baseUrl}/Shahr.svg` },
  '504706': { name: 'شهر', logo: `${baseUrl}/Shahr.svg` },
  '603769': { name: 'صادرات ایران', logo: `${baseUrl}/Saderat.svg` },
  '627961': { name: 'صنعت و معدن', logo: `${baseUrl}/Sanat_Madan.svg` },
  '606373': { name: 'قرض الحسنه مهر ایران', logo: `${baseUrl}/Mehr_Iran.svg` },
  '639599': { name: '(سپه) قوامین', logo: `${baseUrl}/Ghavamin.svg` },
  '627488': { name: 'کارآفرین', logo: `${baseUrl}/Karafarin.svg` },
  '502910': { name: 'کارآفرین', logo: `${baseUrl}/Karafarin.svg` },
  '603770': { name: 'کشاورزی', logo: `${baseUrl}/Keshavarzi.svg` },
  '639217': { name: 'کشاورزی', logo: `${baseUrl}/Keshavarzi.svg` },
  '505416': { name: 'گردشگری', logo: `${baseUrl}/Gardeshgari.svg` },
  '505426': { name: 'گردشگری', logo: `${baseUrl}/Gardeshgari.svg` },
  '636795': { name: 'مرکزی', logo: `${baseUrl}/Bank_Markazi.svg` },
  '628023': { name: 'مسکن', logo: `${baseUrl}/Maskan.svg` },
  '610433': { name: 'ملت', logo: `${baseUrl}/Mellat.svg` },
  '991975': { name: 'ملت', logo: `${baseUrl}/Mellat.svg` },
  '603799': { name: 'ملی ایران', logo: `${baseUrl}/Melli.svg` },
  '639370': { name: 'مهر اقتصاد (سپه)', logo: `${baseUrl}/Mehr_Eghtesad.svg` },
  '627760': { name: 'پست ایران', logo: `${baseUrl}/Postbank.svg` },
  '628157': { name: 'موسسه اعتباری توسعه', logo: `${baseUrl}/Tosee.svg` },
  '505801': { name: '(سپه) موسسه اعتباری کوثر', logo: `${baseUrl}/Kosar.svg` },
  '606256': { name: 'موسسه اعتباری ملل', logo: `${baseUrl}/Melall.svg` },
  '504172': { name: 'رسالت', logo: `${baseUrl}/Resalat.svg` },
}
